pipeline {
    agent any

    parameters {
        string(name: 'FRONTEND_BRANCH', defaultValue: 'docker', description: 'Branch to checkout for Frontend')
    }

    environment {
        BACKEND_URL = 'http://moxi.akifbayram.com:3500'
    }

    stages {
        stage('Cleanup Frontend Container') {
            steps {
                sh 'docker stop moxi-frontend || true'
                sh 'docker rm moxi-frontend || true'
            }
        }

        stage('Checkout Frontend') {
            steps {
                git branch: params.FRONTEND_BRANCH, url: 'https://github.com/Ms-Bean/CS490G-Frontend.git'
            }
        }

        stage('Build and Run Frontend') {
            steps {
                sh 'docker build --build-arg REACT_APP_BACKEND_URL=\$BACKEND_URL -t moxi-frontend .'
                sh 'docker run -d --name moxi-frontend -p 80:80 moxi-frontend'
            }
        }
    }

    post {
        success {
            echo 'Frontend Build and Deployment completed successfully.'
        }
        failure {
            echo 'Frontend Build or Deployment failed.'
        }
    }
}
